# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
      autowire: true      # Automatically injects dependencies in your services.
      autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
      resource: '../../src/AppBundle/*'
      exclude: '../../src/AppBundle{DependencyInjection,Entity,Migrations,Tests,AppBundle.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    AppBundle\Controller\:
      resource: '../../src/AppBundle/Controller'
      tags: ['controller.service_arguments']

    app.deletetask_voter:
      class: AppBundle\Security\TaskVoter
      arguments: ['@security.access.decision_manager']
      tags:
        - { name: security.voter }
      public: false


    AppBundle\DataFixtures\:
      resource: '../../src/AppBundle/DataFixtures'
      tags: ['doctrine.fixture.orm']
      arguments: ['@security.password_encoder']


